name: fluxtube
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.5.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  awesome_bottom_bar: ^1.2.4
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.3+1
  easy_debounce: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_settings_ui: ^3.0.1
  fluttertoast: ^8.2.6
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  go_router: ^14.1.3
  google_fonts: 6.1.0
  injectable: ^2.4.2
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  lottie: ^3.1.2
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  readmore: ^3.0.0
  river_player: ^0.1.3
  share_plus: ^9.0.0
  simple_html_css: ^5.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.10
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.5.2
  injectable_generator: ^2.6.1
  intl_translation: ^0.20.0
  isar_generator: any

dependency_overrides:
  analyzer: ^6.4.1

flutter:

  uses-material-design: true
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_intl:
  enabled: true
  localizely:
    project_id: en

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
